name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "NOW=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
    - name: build and push image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: passerbyflutter/n_m3u8el-re-web
        dockerfile: Dockerfile
        always_pull: true
        tags: ${{ github.ref_name }}